Add functionality to deal with spectral similarity
tnaake/MetNet pull request #19
Opened 2022-02-28 10:31 UTC by LiesaSalzer

Just as discussed with @tnaake I implemented following steps: 

1.  calculation and adding spectral similarity matrices to the structural `AdjacencyMatrix` 
2.  this object can be thresholded by `threshold(am, type = "threshold")` and different filtering options that is defined by the user 
3.  the thresholded `AdjacencyMatrix` can be combined by combine() with the thresholded statistical `AdjacencyMatrix`
4. Updated documentation of functions
5. Added toy example file for MS2 similarity
6. Examples and description in vignette 
7. Unit tests 

Hope everything works for you now!

2022-03-01 08:01 UTC, tnaake requested changes
Hi @LiesaSalzer 

very good! Some small changes only that should not require too much adjustments (mainly removing the calculation of MS2 similaritites within the `addSpectralSimilarity` function).

Many thanks for the great work! 

Best,
Thomas

2022-03-01 08:01 UTC, tnaake commented on NAMESPACE
> +export(addSpectSimil)
could we have a proper name here, rather than the abbreviated one, e.g. `addSpectralSimilarity`?

2022-03-01 08:01 UTC, tnaake commented on R/structural.R
> + return(am_structural)
would it be possible to have only the `adj_spec` object passed to the `addSpectralSimilarity` function? I think it's a bit superfluous to have the `compareSpectra` step in this function as this can also be done outside of `MetNet`. In that case the function would be shorter, more easier to understand, less work to maintain, and we reduce the number of dependencies. In the end it also doesn't matter if the MS2 similarity matrix is created via `Spectra` or some other package. 

We could call the argument `ms2_similarity` (this could be a named list with entries specifying the name of the assay, e.g. `list(ndotproduct = matrix(...), dotproduct = matrix(...)`.

2022-03-01 08:01 UTC, tnaake commented on R/structural.R
> + return(am_structural)
`Spectra` could go into `Suggests` in the DESCRIPTION.

2022-03-01 08:01 UTC, tnaake commented on vignettes/MetNet.Rmd
> +Features from `spectra` will by matched accordingly to the feature names in the
Typo: will be

2022-03-01 08:01 UTC, tnaake commented on tests/testthat/test_spectSimil.R
> +  expect_error(threshold(spect_adj, type = "top1", args = list(n = 2)),
please use throughout Bioc coding style. FOr instance, spaces properly (see e.g. `c("binary","group","formula","mass","ndotproduct")` and intendations of 4.

2022-03-01 08:01 UTC, tnaake commented on vignettes/MetNet.Rmd
> +Further, the spectral similarity matrix can be thresholded using the function threshold.
should be 'function `threshold`'

2022-03-01 08:01 UTC, tnaake commented on vignettes/MetNet.Rmd
> +If multiple methods have been used to generate the spectral matrices, different threshold parameters can be defined (for detailed description see thresholding of statstical)
statistical

2022-03-01 08:01 UTC, tnaake commented on tests/testthat/test_spectSimil.R
> +  expect_equal(as.vector(assay(spect_adj, "ndotproduct")[7,1:10]),
for testing purposes a MS2 similarity matrix can be stored as an `RData` object in `MetNet` to avoid dependency on `Spectra`. There can be then a small script on how this matrix was created.

2022-03-01 08:01 UTC, tnaake commented on R/statistical.R
>  #' @aliases threshold
the function `threshold` should be moved to `combine.R` as it is used now by both `statistical` and `structural`.

2022-03-03 16:00 UTC, LiesaSalzer commented
Hi @tnaake, 
Thanks for your feedback! 
I try to address all your comments in the last commit. 
I think it should be fine now :)

2022-03-03 17:02 UTC, tnaake approved these changes

2022-03-03 17:02 UTC, tnaake commented
Many thanks, for the PR :) Looks great @LiesaSalzer !

2022-03-03 17:02 UTC, merged